server.port=9090
main-server.url=http://localhost:8080
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:6642/stat
#spring.datasource.username=
#spring.datasource.password=
